---
- name: Ansible for Docker Installation
  hosts: myhost

  vars:
    - docker_list_file_path: /etc/apt/sources.list.d/docker.list
    - docker_list_file_content: deb https://apt.dockerproject.org/repo ubuntu-trusty main

  tasks:
    - name: install dependencies
      become: yes
      become_method: sudo
      apt: name={{ item }} update_cache=yes state=latest
      with_items: 
        - apt-transport-https
        - ca-certificates
    - name: add new gpg key
      become: yes
      become_method: sudo
      shell: "{{ item }}"
      with_items: 
        - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - name: create docker list file
      become: yes
      become_method: sudo
      file: path="{{ docker_list_file_path }}" state=touch
    - name: set state for docker file
      stat: path="{{ docker_list_file_path }}"
      register: docker_file
    - name: add content for docker list file
      become: yes
      become_method: sudo
      copy: content="{{ docker_list_file_content }}" dest="{{ docker_list_file_path }}" owner=root
      when: docker_file.stat.exists == true
    - name: install docker engine
      become: yes
      become_method: sudo
      apt: name={{ item }} update_cache=yes state=latest
      with_items: 
        - docker-engine
    - name: start docker engine service
      service: name=docker state=started
